apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: nodejs-cj
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          name: nodejs-job
        spec:
          restartPolicy: Never
          containers:
            - name: nodejs-console
              image: darkking/nodejs-console